### PR TITLE
Keyboard elements

### PR DESCRIPTION
**Pull request by gingerbeardman**
All keyboard layouts except Emoji & Dictation

### CODE REVIEW

**Comment by rafaelconde** [comment]
Can you help me figure out what changed? :)

**Comment by gingerbeardman** [comment]
I added a new file with my changes, so you can cut and paste into the main file. See the files changed tab, above.

What did I do? I took the bitmaps of the keyboards, and created vector versions.

**Comment by gingerbeardman** [comment]
Hey, no need to name me in the readme. Happy to have helped and learnt some Sketch along the way.

**Comment by rafaelconde** [comment]
Are you kidding, it's the least I can do :)

Thank you.

**Pull request merged**
